# Generated by Django 5.0.2 on 2024-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
