# Generated by Django 5.0.2 on 2024-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_oneword_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='oneword_review',
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=20, null=True),
        ),
    ]
