# Generated by Django 5.0.2 on 2024-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_review_oneword_review_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=20),
        ),
    ]
